---
- name: Build free tier EC2 instance
  hosts: localhost
  connection: local
  gather_facts: False

  vars:
    region: us-east-1
    name: "server-nginx"
    sec_group: "{{ name }}-sec-group"
    instance_type: t2.micro
    count: 2
    keypair: Nginx-challenge
    image_id: ami-053b0d53c279acc90

  tasks:

    - name: "create security group"
      ec2_group:
        name: "{{ sec_goup }}"
        description: "Security group for instance ec2 {{ name }}"
        region: "${{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on ssh port

          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all http port
        rules_egress:
          - proto: tcp
            from_port: 80
            to_pot: 80
            cidr_ip: 0.0.0.0/0
            group_desc: create another sec_group
      register: sec_group_id

    - name: "provision an EC2 instance"
      ec2:
        key_name: "{{ keypair }}"
        count: {{ count }}
        name: "{{ name }}-{{ count.index }}"
        image_id: "{{ image_id }}"
        instance_type: "{{ instance_type }}"
        region: "{{ region }}"
        secutity_group: "{{sec_group_id.group_id}}"
        network:
          assing_public_ip: true
        tags:
          Environment: Testing
        Wait: true
      register: instance_ec2

    - name: Print all instances
        debug:
          var: instance_ec2
