---
- name: List all EC2 instances
  hosts: localhost
  gather_facts: false
  vars:
    region: us-east-1
  tasks:
    - name: Get all instances
      ec2_instance_info:
        region: "{{ region }}"
      register: ec2_info

    - name: Print all instances
      debug:
        var: ec2_info.instances
